### PR TITLE
Add trove tags for supported Python versions and a tox.ini

### PR DESCRIPTION
**Pull request by public**
3.2 support would require some workaround for the unicode literals that are used, perhaps by adding six as a dependency.

This will make ua-parser show up as supporting Py3 on sites like http://py3readiness.org/ and in tools like https://github.com/brettcannon/caniusepython3

### CODE REVIEW

**Comment by hwkns** [comment]
:+1:

**Comment by commenthol** [comment]
@public can you please commit your changes to https://github.com/ua-parser/uap-python as this project has moved.

**Comment by public** [comment]
Yep.

**Comment by public** [comment]
https://github.com/ua-parser/uap-python/pull/8

**Pull request closed without merging**
